# SITE CONFIGURATION
baseurl: ""
url: "https://kylereddoch.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Kyle Reddoch                                    # site's title
description: "Hello, my name is Kyle Redddoch! This is my
  website dedicated to everything Apple with a
  focus on Siri Shortcuts. Hope you enjoy. I will
  be sharing my personal shortcuts that I create
  as well as news, tips, and more."      # used by search engines
avatar: /assets/img/avatar.png                         # Empty for no avatar in navbar
favicon: /assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Hello, I'm Kyle 👋🏼  # Change Blog header text
header_feature_image: /assets/img/pexels/book-glass.jpeg
footer_text: >
  Made with ☕️ by Kyle Reddoch. Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>. Hosted on <a href="https://kylereddoch.github.io">Github Pages</a>.

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: dark                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

theme: type-on-strap                                  # if using the theme as a jekyll theme gem
# remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
